# Flusso di lavoro per costruire e distribuire il sito su GitHub Pages
name: Deploy GitHub Pages site

on:
  # Eseguito quando viene effettuato un push sul branch `main`
  push:
    branches: ["main"]
  # Permette di eseguire questo workflow manualmente dalla tab Actions
  workflow_dispatch:

# Imposta i permessi del GITHUB_TOKEN per permettere la distribuzione su GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permette una sola distribuzione concorrente, annullando le esecuzioni in coda o in corso.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job di build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install esbuild
        run: npm install -g esbuild
      - name: Create dist directory
        run: mkdir dist
      - name: Build with esbuild
        run: esbuild index.tsx --bundle --outfile=dist/bundle.js --loader:.tsx=tsx
      - name: Copy index.html to dist
        run: cp index.html dist/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Carica la cartella dist
          path: './dist'
      
  # Job di distribuzione
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
